all:
  vars:
    ansible_user: kosa
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3
    kubernetes_api_vip: 172.16.43.99
  hosts:
    k8s-cp-1:
      ansible_host: 172.16.43.100
      vm_id: 201
      proxmox_node: kosa-team3-01
      vlan_id: 30
    k8s-cp-2:
      ansible_host: 172.16.43.101
      vm_id: 202
      proxmox_node: kosa-team3-02
      vlan_id: 30
    k8s-cp-3:
      ansible_host: 172.16.43.102
      vm_id: 203
      proxmox_node: kosa-team3-03
      vlan_id: 30
    k8s-worker-1:
      ansible_host: 172.16.43.110
      vm_id: 211
      proxmox_node: kosa-team3-01
      vlan_id: 30
    k8s-worker-2:
      ansible_host: 172.16.43.111
      vm_id: 212
      proxmox_node: kosa-team3-02
      vlan_id: 30
    k8s-worker-3:
      ansible_host: 172.16.43.112
      vm_id: 213
      proxmox_node: kosa-team3-03
      vlan_id: 30
    lb-1:
      ansible_host: 172.16.42.100
      vm_id: 221
      proxmox_node: kosa-team3-04
      vlan_id: 20
    lb-2:
      ansible_host: 172.16.42.101
      vm_id: 222
      proxmox_node: kosa-team3-05
      vlan_id: 20
    bastion:
      ansible_host: 172.16.44.100
      vm_id: 231
      proxmox_node: kosa-team3-01
      vlan_id: 40
    monitoring:
      ansible_host: 172.16.44.101
      vm_id: 232
      proxmox_node: kosa-team3-04
      vlan_id: 40
    argocd:
      ansible_host: 172.16.44.102
      vm_id: 233
      proxmox_node: kosa-team3-03
      vlan_id: 40
    mariadb-1:
      ansible_host: 172.16.43.160
      vm_id: 241
      proxmox_node: kosa-team3-05
      vlan_id: 30
  children:
    k8s:
      children:
        control_plane:
        worker:
    control_plane:
      hosts:
        k8s-cp-1:
        k8s-cp-2:
        k8s-cp-3:
    worker:
      hosts:
        k8s-worker-1:
        k8s-worker-2:
        k8s-worker-3:
    load_balancer:
      hosts:
        lb-1:
        lb-2:
    bastion:
      hosts:
        bastion:
    monitoring:
      hosts:
        monitoring:
    argocd:
      hosts:
        argocd:
    database:
      hosts:
        mariadb-1:
