apiVersion: v1
kind: ConfigMap
metadata:
  name: flaskapp-config
  namespace: flaskapp-prod
data:
  DATABASE_HOST: "172.16.43.160"
  DATABASE_USER: "kosa"
  DATABASE_DB_NAME: "employees"
  AWS_DEFAULT_REGION: "ap-northeast-2"
  PHOTOS_BUCKET: "flaskapp-proddata-kosa-project-team3-snow-lai9z"
