apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  namespace: flaskapp-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
        - name: flaskapp
          image: <ECR_URL>/flaskapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: flaskapp-config
            - secretRef:
                name: flaskapp-secret
