kubernetes_repo_version: "v1.30"
kubernetes_package_version: "1.30.1-1.1"
kubernetes_cluster_version: "v1.30.1"
kubernetes_api_port: 6443
kubernetes_pod_cidr: "10.244.0.0/16"
kubernetes_service_cidr: "10.96.0.0/12"
kube_vip_version: "v0.8.9"
calico_version: "v3.28.5"
kubernetes_packages:
  - "kubelet={{ kubernetes_package_version }}"
  - "kubeadm={{ kubernetes_package_version }}"
  - "kubectl={{ kubernetes_package_version }}"

common_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gpg
  - containerd
  - qemu-guest-agent

k8s_kernel_modules:
  - overlay
  - br_netfilter

k8s_sysctl:
  net.bridge.bridge-nf-call-ip6tables: "1"
  net.bridge.bridge-nf-call-iptables: "1"
  net.ipv4.ip_forward: "1"
